# Generated by Django 5.2 on 2025-04-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('vendido', 'Vendido'), ('alugado', 'Alugado'), ('reservado', 'Reservado')], default='disponivel', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('comercial', 'Comercial'), ('rural', 'Rural')], max_length=20)),
                ('negocio', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')], max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quartos', models.PositiveIntegerField(default=0)),
                ('banheiros', models.PositiveIntegerField(default=0)),
                ('vagas_garagem', models.PositiveIntegerField(default=0)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('descricao', models.TextField()),
                ('destaque', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/')),
                ('principal', models.BooleanField(default=False)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='Imob.imovel')),
            ],
        ),
    ]
