# Generated by Django 5.2 on 2025-04-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Terreno', 'Terreno'), ('Comercial', 'Comercial')], max_length=20)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=300)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quartos', models.PositiveIntegerField()),
                ('banheiros', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField(help_text='Área em metros quadrados')),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Alugado/Vendido', 'Alugado/Vendido')], default='Disponível', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imoveis/')),
            ],
        ),
    ]
