# Generated by Django 5.2 on 2025-04-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imob', '0002_alter_imovel_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
